export CHROMIUM_FLAGS="--ozone-platform-hint=wayland --force-device-scale-factor=1.0"
export GOOGLE_API_KEY="no"
export GOOGLE_DEFAULT_CLIENT_ID="0"
export GOOGLE_DEFAULT_CLIENT_SECRET="0"
export LANG=@LOCALE@
export LC_ALL=@LOCALE@
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
    export XDG_RUNTIME_DIR="/run/user/$(id -u)"
    if [ ! -d "$XDG_RUNTIME_DIR" ]; then
        mkdir -p "$XDG_RUNTIME_DIR"
        chmod 700 "$XDG_RUNTIME_DIR"
    fi
    export XDG_SESSION_TYPE=wayland
    export XDG_CURRENT_DESKTOP=KDE
    export QT_QPA_PLATFORM=wayland
    exec dbus-run-session startplasma-wayland
fi
unset HISTFILE
